"""Scan history and exports (CSV and a print-friendly HTML page)."""

import csv
import io
import json
from html import escape

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import HTMLResponse, Response
from sqlalchemy import select
from sqlalchemy.orm import Session

from backend.auth import current_user
from backend.db import get_db
from backend.models import Scan, User
from backend.results import scan_to_dict
from backend.tools import TOOLS

router = APIRouter(prefix="/api/scans", tags=["reports"])

HISTORY_LIMIT = 100
CSV_COLUMNS = ["scan_id", "tool", "target", "date", "severity", "title", "explanation", "fix", "details"]
# The report page has no scripts, so it can use a very strict policy.
REPORT_CSP = "default-src 'none'; style-src 'unsafe-inline'"


def tool_label(tool: str) -> str:
    return TOOLS[tool].LABEL if tool in TOOLS else tool


def get_own_scan(db: Session, user: User, scan_id: int) -> Scan:
    """Users only see their own scans; someone else's scan looks exactly like a missing one."""
    scan = db.get(Scan, scan_id)
    if scan is None or scan.user_id != user.id:
        raise HTTPException(404, "Scan not found")
    return scan


@router.get("")
def list_scans(user: User = Depends(current_user), db: Session = Depends(get_db)):
    """The logged-in user's scans, newest first."""
    scans = db.scalars(select(Scan).where(Scan.user_id == user.id).order_by(Scan.id.desc()).limit(HISTORY_LIMIT))
    history = []
    for scan in scans:
        severities = [finding["severity"] for finding in scan.findings]
        history.append({
            "id": scan.id,
            "tool": scan.tool,
            "label": tool_label(scan.tool),
            "target": scan.target,
            "created_at": scan.created_at.isoformat(),
            "counts": {level: severities.count(level) for level in ("high", "medium", "low")},
        })
    return history


@router.get("/{scan_id}")
def get_scan(scan_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    return scan_to_dict(get_own_scan(db, user, scan_id))


# --- CSV ---


def safe_cell(value: str) -> str:
    """Stop spreadsheet apps from running a cell as a formula (CSV injection).

    A target or log line such as "=HYPERLINK(...)" would otherwise become a live
    formula when the CSV is opened in Excel.
    """
    return "'" + value if value[:1] in ("=", "+", "-", "@") else value


def scan_to_csv(scan: Scan) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(CSV_COLUMNS)
    rows = scan.findings or [{"severity": "", "title": "No problems found", "explanation": "", "fix": "",
                              "details": {}}]
    for finding in rows:
        row = [str(scan.id), scan.tool, scan.target, scan.created_at.isoformat(), finding["severity"],
               finding["title"], finding["explanation"], finding["fix"], json.dumps(finding["details"])]
        writer.writerow([safe_cell(cell) for cell in row])
    return output.getvalue()


@router.get("/{scan_id}/export.csv")
def export_csv(scan_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    scan = get_own_scan(db, user, scan_id)
    return Response(
        scan_to_csv(scan),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="sentinel-scan-{scan.id}.csv"'},
    )


# --- Print-friendly HTML ---

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Sentinel Lite report #{id}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; color: #1d2330; }}
  .meta, .hint {{ color: #5f6878; }}
  .finding {{ border: 1px solid #dde1e7; border-left-width: 6px; padding: 0.5rem 1rem; margin: 1rem 0; break-inside: avoid; }}
  .high {{ border-left-color: #b42318; }} .medium {{ border-left-color: #b54708; }} .low {{ border-left-color: #2e6b30; }}
  .severity {{ text-transform: uppercase; font-size: 0.8rem; font-weight: 700; }}
  pre {{ background: #f5f6f8; padding: 0.5rem; white-space: pre-wrap; }}
  @media print {{ .hint {{ display: none; }} }}
</style>
</head>
<body>
<p class="hint">To save as PDF: press Ctrl+P (Cmd+P on Mac) and choose "Save as PDF".</p>
<h1>{label}: {target}</h1>
<p class="meta">Scan #{id} &middot; {date} &middot; {count} finding(s)</p>
<h2>Findings</h2>
{findings}
<h2>Raw summary</h2>
<pre>{summary}</pre>
<p class="meta">Generated by Sentinel Lite.</p>
</body>
</html>
"""

FINDING = """<div class="finding {severity}">
<p class="severity">{severity}</p>
<h3>{title}</h3>
<p>{explanation}</p>
<p><strong>How to fix:</strong> {fix}</p>
<p class="meta">{details}</p>
</div>"""


def scan_to_html(scan: Scan) -> str:
    """Every value is passed through escape(), so a target or log line can't inject HTML."""
    findings = "\n".join(
        FINDING.format(
            severity=escape(f["severity"]),
            title=escape(f["title"]),
            explanation=escape(f["explanation"]),
            fix=escape(f["fix"]),
            details=escape(", ".join(f"{key}: {value}" for key, value in f["details"].items())),
        )
        for f in scan.findings
    )
    return PAGE.format(
        id=scan.id,
        label=escape(tool_label(scan.tool)),
        target=escape(scan.target),
        date=escape(scan.created_at.strftime("%Y-%m-%d %H:%M UTC")),
        count=len(scan.findings),
        findings=findings or "<p>No problems found.</p>",
        summary=escape(json.dumps(scan.summary, indent=2)),
    )


@router.get("/{scan_id}/report")
def export_html(scan_id: int, user: User = Depends(current_user), db: Session = Depends(get_db)):
    """A standalone HTML page the user can print or "Save as PDF"."""
    scan = get_own_scan(db, user, scan_id)
    return HTMLResponse(scan_to_html(scan), headers={"Content-Security-Policy": REPORT_CSP})
